apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: url-shortener-alerts
  namespace: monitoring
spec:
  groups:
  - name: url-shortener
    rules:
    - alert: HighErrorRate
      expr: rate(flask_http_request_total{status=~"5.."}[5m]) / rate(flask_http_request_total[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate on URL shortener"
        description: "Error rate is {{ $value }}%"