services:
  worker:
    build: ./src/worker
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-defaultpassword}  # Add password
      
  api:
    build:
      context: .  # Build from project root
      dockerfile: src/api/Dockerfile
    ports:
      - "5050:5000"
    environment:
      - DOMAIN=http://localhost:5050
      - LD_LIBRARY_PATH=/usr/local/lib
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - PATH=/usr/bin:/usr/local/bin:$PATH
      - PYTHONPATH=/app:$PYTHONPATH
      

    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-defaultpassword}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-defaultpassword}
    volumes:
      - redis_data:/data

  test:
    build:
      context: .
      dockerfile: src/api/Dockerfile
      target: tester
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - PATH=/usr/bin:/usr/local/bin:$PATH
      - PYTHONPATH=/app:$PYTHONPATH
    depends_on:
      - redis
    command: sh -c "cd src/api && python -m pytest -v --cov=app --cov-report=term"
volumes:
  redis_data: