apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer  # Changed from NodePort
  selector:
    app: url-shortener
    tier: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000