apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment  # Ensure this matches
  labels:
    app: url-shortener
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      tier: worker
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"  # Matches worker's port
      labels:
        app: url-shortener
        tier: worker
    spec:
      containers:
      - name: worker
        image: worker-image:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        - name: REDIS_HOST
          value: "redis-service"