name: CI Pipeline

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  api-ci:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase image name
        id: vars
        run: echo "IMAGE_NAME_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build API image (production)
        run: |
          cd src/api
          docker build -t $REGISTRY/${IMAGE_NAME_LC}-api:${{ github.sha }} .

      - name: Build API image (test stage)
        run: |
          cd src/api
          docker build --target tester -t $REGISTRY/${IMAGE_NAME_LC}-api-tester:${{ github.sha }} .

      - name: Run API tests
        run: |
          cd src/api
          docker run --network host -e REDIS_HOST=localhost \
            $REGISTRY/${IMAGE_NAME_LC}-api-tester:${{ github.sha }} \
            pytest -v --cov=app --cov-report=xml

      - name: Debug variables
        run: |
          echo "REGISTRY: $REGISTRY"
          echo "IMAGE_NAME_LC: $IMAGE_NAME_LC"
          echo "Image name: $REGISTRY/${IMAGE_NAME_LC}-api:${{ github.sha }}"

      - name: Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $REGISTRY/${{ env.IMAGE_NAME_LC }}-api:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  worker-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Worker
        run: |
          cd src/worker
          go build -v -o url-shortener-worker
